config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :events, except: [:destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  after_create :new_attendance_send

  def admin
    event.admin
  end

  private 

  def new_attendance_send
    UserMailer.new_attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, :duration, :title, :description, :price, :location, presence: :true
  validate :cant_be_past
  validate :duration_5_pos
  validates :title, length: { in: 5..140}
  validates :description, length: { in: 20..1000 }
  validate :price_validation
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :users, through: :attendances

  def self.convert_date_time(date, time)
    (date.to_s + " " +time.to_s).to_datetime
  end

  def duration_display
    duration < 59 ? duration.to_s + " mins" : (duration/60).to_s + "h+"
  end

  def end_date
    start_date + duration * 60
  end

  private 
  
  def cant_be_past
    if start_date.nil?
      errors.add(:start_date, "must be filled") 
    else
      errors.add(:start_date, "cant be past") if start_date < Time.now
    end
  end
  
  def duration_5_pos
    if duration.nil?
      errors.add(:duration, "must be filled") 
    else
      errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0
      errors.add(:duration, "has to be a positive amount of minutes") unless duration > 0
    end
  end

  def price_validation
    if price.nil?
      errors.add(:price, "must be filled") 
    else
      errors.add(:price, "cant be free") if price < 1
      errors.add(:price, "cant be over 1000") if price > 1000
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances
  has_many :administrated_events, class_name: 'Event', foreign_key: 'admin_id'
  after_create :welcome_send

  private 

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :description, :email, :password)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.start_date = Event.convert_date_time(params[:date], params[:hour])
    @event.admin = current_user
    puts event_params
    if @event.save
      redirect_to @event
    else 
      @date = params[:date]
      @hour = params[:hour]
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :price, :duration)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  before_action :user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end
  
  def check_user
    redirect_to current_user unless current_user.id.to_i == params[:id].to_i
  end

  def user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<section class="jumbotron text-center text-white">
  <div class="container">
    <h1 class="jumbotron-heading text-white">Pour ceux qui adorent sortir</h1>
    <p class="lead">Trouvez ici rapidement des évènements près de chez vous.</p>
    <p id="bouton-jumbotron"><%= link_to "Créer un évènement", new_event_path, class: "btn btn-primary" %></p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <h3 class="mt-3 mb-3">Évènements à proximité:</h3>
    <div class="card-columns">
      <% @events.each do |e| %>
        <div class="card mb-4 box-shadow border-primary">
          <!-- <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap"> -->
          <div class="card-header">
            <p>"<%= e.title %>"</p>
            <div class="card-price">
              <%= e.price %>€
            </div>
            <div class="card-duration">
              <%= e.duration_display %>
            </div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= e.description %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to "Voir", event_path(e.id), class:"btn btn-sm btn-outline-primary" %>
              </div>
              <small class="text-muted"><%= e.start_date.strftime("%d/%m/%Y à %H:%M") %></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-10rem">
  <h2 class="text-center">Créer un évènement</h2>
  <% if @event.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <ul>
        <% @event.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <div class="row">
    <div id="form-new" class="col-md-6 offset-md-3 mt-3 pt-5 pb-5 p-3">
      <%= form_for @event do |f| %>
        <div class="form-group">
          <%= f.label :titre %><br />
          <%= f.text_field :title, autofocus: true, class:"form-control", required:"true"%>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, autofocus: true, class:"form-control", required:"true" %>
        </div>
        <div class="form-group">
          <div class="form-row">
            <div class="col-6">
              <%= f.label :date_de_début %><br />
              <input type="date" name="date" class="form-control" value="<%= @date %>"required></input>
            </div>
            <div class="col-6">
              <%= f.label :heure_de_début %><br />
              <input type="time" name="hour" class="form-control" value="<%= @hour %>" required></input>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="form-row">
            <div class="col-6">
              <%= f.label :prix %><br />
              <%= f.number_field :price, autofocus: true, class:"form-control", required:"true" %>
            </div>
            <div class="col-6">
              <%= f.label :durée %><br />
              <%= f.number_field :duration, autofocus: true, class:"form-control", required:"true" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :lieu %><br />
          <%= f.text_field :location, autofocus: true, class:"form-control", required:"true" %>
        </div>
        <%= f.submit "Créer", class:"btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container mt-10rem">
  <h2 class="text-center">Page Evenement</h2>
  <div class="card mt-5 text-center bg-light border-primary box-shadow" style="width: 100%;">
    <h2 class="card-title mt-3 text-primary"><%= @event.title %></h2>
    <div class="card-body">
      <p class="card-text"><strong>Description</strong>:</p>
      <p><%= @event.description %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Inscrits</strong>: <%= @event.attendances.count %></li>
      <li class="list-group-item"><strong>Début</strong>: <%= @event.start_date.strftime("%d/%m/%Y à %H:%M") %> </li>
      <li class="list-group-item"><strong>Fin</strong>: <%= @event.end_date.strftime("%d/%m/%Y à %H:%M") %> </li>
      <li class="list-group-item"><strong>Lieu</strong>: <%= @event.location %> </li>
      <li class="list-group-item"><strong>Prix</strong>: <%= @event.price %> € </li>
    </ul>
    <div class="card-body row">
      <div class="col-md-3 col-6 text-center offset-md-3">
        <strong>Organisateur</strong>: <%= link_to @event.admin.email, "mailto:"+@event.admin.email, class:"card-link" %>
      </div>
      <div class="col-3">
        <%= link_to "S'inscrire", "#" , class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>EventbriteProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="height: 4rem">
        <a class="navbar-brand" href="<%= root_path %>">PACEVENTBRITE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse bg-primary navbar-dark" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item <%="active" if current_page? root_path %>">
              <a class="nav-link" href="<%= root_path %>">Accueil <span class="sr-only"><%="(actuel)" if current_page? root_path %></span></a>
            </li>
            <li class="nav-item <%="active" if current_page? new_event_path %>">
              <a class="nav-link" href="<%= new_event_path %>">Créer un évènement <span class="sr-only"><%="(actuel)" if current_page? new_event_path %></span></a>
            </li>
            <% unless user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle <%= "active" if current_page? new_user_registration_path %><%= "active" if current_page? new_user_session_path %>" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  S'inscrire / Se connecter
                </a>
                <div class="dropdown-menu bg-primary " aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item text-white" href="<%= new_user_registration_path %>">S'inscrire</a>
                  <a class="dropdown-item text-white" href="<%= new_user_session_path %>">Se connecter</a>
                </div>
              </li>
            <% else %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle <%= "active" if current_page? user_path(current_user.id) %>" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mon profil
                </a>
                <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item text-white" href="<%= user_path(current_user.id) %>">Mon profil</a>
                  <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item text-white"%>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main style="margin-top: 4rem;">
      <%= yield %>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mt-10rem">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="text-center">Modifier votre profil</h2>

      <%= form_for @user do |f| %>
        <div class="form-group mt-5">
          <div class="form-row">
            <div class="col-md-6">
              <%= f.label :prénom %><br />
              <%= f.text_field :first_name, autofocus: true, class:"form-control", required: true %>
            </div>

            <div class="col-md-6">
              <%= f.label :nom %><br />
              <%= f.text_field :last_name, autofocus: true,  class:"form-control", required: true  %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, autofocus: true, class:"form-control", required:"true" %>
        </div>
        <%= f.submit "Confirmer les changements", class:" mt-5 btn btn-primary btn-block" %>
      <% end %>
      <%= link_to "Retour au profil", user_path(@user.id) %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-10rem">
<h1 class="text-center"><%= @user.first_name.capitalize + " " +@user.last_name.capitalize %> </h1>
  <div class="row mt-5">
    <div class="col-md-4 text-center">
      <h2>Votre profil</h2>
      <div class="card border-primary mt-3 mb-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Prénom</strong>: <%=@user.first_name.capitalize %> </li>
          <li class="list-group-item"><strong>Nom</strong>: <%=@user.last_name.capitalize %> </li>
          <li class="list-group-item"><strong>Description</strong>: <%=@user.description %></li>
          <li class="list-group-item"><strong>Email</strong>: <%=@user.email %> </li>
        </ul>
      </div>
      <p><%= link_to "Editer votre profil", edit_user_path(@user.id), class: "btn btn-primary" %></p>
      <p><%= link_to "Editer votre compte", edit_user_registration_path(@user.id), class: "btn btn-light" %></p>
    </div>
    <div class="col-md-8 text-center"> 
      <h2>Vos évènements</h2>
        <% if @user.administrated_events.count == 0 %> 
          <strong class="mt-3 mb-3">Vous n'avez pas encore crée d'évènement </strong>
        <% else %>
          <strong>Vous avez crée <%= @user.administrated_events.count %> événement<%= @user.administrated_events.count > 1 ? "s" : "" %></strong>
          <p>Liste des évènements que vous organisez:</p>
          <div class="card border-primary  mt-3 mb-3">
            <ul class="list-group list-group-flush">
              <% @user.administrated_events.each do |e| %>
                <li class="list-group-item"><%= link_to e.title.capitalize, event_path(e.id) %> à <em><%= e.location %></em>
                  <% unless e.users.count == 0 %>
                    qui séduit déjà <%= e.users.count %> utilisateur<%= e.users.count > 1 ? "s" : "" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %> 
        <p><%= link_to "Créer un évènement", new_event_path, class: "btn btn-primary" %></p> 
      </div>
    </div>     
  </div>     
</div>